### ISSUE TITLE
python3.4 test failed on debian build in chroot

### ISSUE THREAD

**Issue by faunris** [tk0miya/testing.common.database#3]
Hello.
I use this code for build deb package testing.posgresql:

debain/control:

```
#!/usr/bin/make -f
export PYBUILD_NAME=testing.common.database
%:
    dh $@ --with python2,python3 --buildsystem=pybuild
```

this is debian jessie
install dh_python, python3-nose, etc

nose test on python 2.7 finish ok
but nose test on python 3.4 failed:

```
/usr/lib/python3.4/unittest/case.py:605: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmprcvrgg1s/Postgresql.log' mode='wt' encoding='ANSI_X3.4-1968'>
  outcome.errors.clear()

Traceback (most recent call last):
  File "/tmp/buildd/testing.postgresql-1.3.0/tests/test_postgresql.py", line 142, in test_stop_on_child_process
    pgsql = testing.postgresql.Postgresql()
  File "/usr/lib/python3/dist-packages/testing/common/database.py", line 89, in __init__
    self.start()
  File "/usr/lib/python3/dist-packages/testing/common/database.py", line 136, in start
    os.dup2(logger.fileno(), sys.__stdout__.fileno())
ValueError: underlying buffer has been detached
```

maybe rewrite this code to subproccess?

**Comment by tk0miya** [comment]
Thank you for reporting.
I already rewrote it to subprocess in HEAD.
Could you retry with it?

If it works fine, I will release it as new version.

**Comment by faunris** [comment]
Amazing!
All test complete successful!
We are waiting for release. Thank you very much, and hello from Russia Ideco PBX.

**Comment by tk0miya** [comment]
Thank you for confirmation!
I'll release it in nearly future. (Sorry, I'm busy now. so I can't work for release a while)
